# f = open("Demo.txt", "w")
f = open("Demo.txt", "a")
# f.write("Hello This is me I want to write something")
# f.write(" Hello This is me I want to write new text")
f.write(" I am appending something to the existing code")
f.close()
f = open("Demo.txt", "r")
print(f.read())
f.close()